# Generated by Django 4.1.7 on 2023-03-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ABC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gtin", models.CharField(max_length=200)),
                ("revenue", models.DecimalField(decimal_places=2, max_digits=12)),
                ("share", models.FloatField()),
                ("ABC", models.CharField(max_length=1)),
                ("share_cum", models.DecimalField(decimal_places=5, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gtin", models.CharField(max_length=200)),
                ("defect_lvl", models.FloatField()),
            ],
        ),
    ]
