# Generated by Django 4.1.7 on 2023-03-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataprofit", "0002_abc_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price_min_max",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gtin", models.CharField(max_length=200)),
                ("price_min", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_max", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
